apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: ngnix
    tier: dev
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: DEMO_GREETING
      value: "Hello from the envirnoment" 
    - name: DEMO_FAREWWLL
      value: "Such a sweet Sorrow" 
