apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment2
  name: my-service2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31112
  selector:
    app: nginx-deployment2
  type: NodePort
