apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment2
  name: nginx-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment2
  template:
    metadata:
      labels:
        app: nginx-deployment2
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
